/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piproject.ui;

import piproject.mysql.MySQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class UIConsultarUsers extends javax.swing.JFrame {

    /**
     * Creates new form UIConsultarUsers
     */
    public UIConsultarUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        rankLabel = new javax.swing.JLabel();
        pontosLabel = new javax.swing.JLabel();
        changeNameButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        porcentagemLabel = new javax.swing.JLabel();
        AlterarNomeField = new javax.swing.JTextField();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(new java.awt.Color(51, 153, 255));
        backButton.setFont(new java.awt.Font("Impact", 1, 40)); // NOI18N
        backButton.setText("Voltar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 950, 317, 54));

        jLabel11.setFont(new java.awt.Font("Impact", 3, 96)); // NOI18N
        jLabel11.setText("Consulta de Usuários - ADM");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 1210, -1));

        IDTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        IDTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite o ID do usuário para ser consultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai", 1, 14))); // NOI18N
        getContentPane().add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 640, 80));

        userLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        userLabel.setText("User: ?");
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));

        rankLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        rankLabel.setText("Rank: ?");
        getContentPane().add(rankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, -1, -1));

        pontosLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        pontosLabel.setText("Pontuação: ?");
        getContentPane().add(pontosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, -1, -1));

        changeNameButton.setBackground(new java.awt.Color(51, 153, 255));
        changeNameButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        changeNameButton.setText("Alterar Nome");
        changeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changeNameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 870, 120, 40));

        deleteUserButton.setBackground(new java.awt.Color(51, 153, 255));
        deleteUserButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deleteUserButton.setText("Excluir Usuário");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 870, 130, 40));

        searchButton.setBackground(new java.awt.Color(51, 153, 255));
        searchButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        searchButton.setText("Buscar Usuário");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, 50));

        porcentagemLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        porcentagemLabel.setText("Porcentagem De Acertos: ?");
        getContentPane().add(porcentagemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, -1, -1));

        AlterarNomeField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AlterarNomeField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite o nome para ser trocado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        getContentPane().add(AlterarNomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 780, 390, 60));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piproject/api/back.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        UIInicioADM frame = new UIInicioADM();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try (Connection con = MySQL.getConnection();) {
            Statement stmt = con.createStatement();
            String SQLUser = "SELECT userName, userRank, userPoints FROM `piproject`.`user_informations` WHERE userID=" + IDTextField.getText();
            ResultSet rs = stmt.executeQuery(SQLUser);

            if (rs.next()){
                String nome_user = rs.getString("userName");
                String rank = rs.getString("userRank");
                String pontos = rs.getString("userPoints");
                userLabel.setText("User: " + nome_user);
                rankLabel.setText("Rank: " + rank);
                pontosLabel.setText("Pontuação: " + pontos);
                
            }else 
            {
                JOptionPane.showMessageDialog(null, "ID Desconhecido!");
            }
            
        } catch (Exception e) {
                    System.err.println(e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void changeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameButtonActionPerformed
        // TODO add your handling code here:
        try (Connection con = MySQL.getConnection();) {
            Statement stmt = con.createStatement();
            String SQLUpdate = "UPDATE `piproject`.`user_informations` SET `userName` ='" + AlterarNomeField.getText() +"' WHERE `userID` =" + IDTextField.getText() + ";";
            stmt.executeUpdate(SQLUpdate);
            JOptionPane.showMessageDialog(null, "Usuário " + IDTextField.getText() + " teve o nome alterado!");
            
        } catch (Exception e) {
                    System.err.println(e);
        }
    }//GEN-LAST:event_changeNameButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        // TODO add your handling code here:
        try (Connection con = MySQL.getConnection();) {
            Statement stmt = con.createStatement();
            String SQLDelete = "DELETE FROM user_informations WHERE userID =" + IDTextField.getText() + ";";
            stmt.executeUpdate(SQLDelete);
            JOptionPane.showMessageDialog(null, "Usuário " + IDTextField.getText() + " foi deletado!");
        } catch (Exception e) {
                    System.err.println(e);
        }
            
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIConsultarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIConsultarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIConsultarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIConsultarUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIConsultarUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlterarNomeField;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton changeNameButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel pontosLabel;
    private javax.swing.JLabel porcentagemLabel;
    private javax.swing.JLabel rankLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
