/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piproject.ui;

import piproject.mysql.MySQL;

import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 * @author rafae
 */
public class UIInicio extends javax.swing.JFrame {

    /**
     * Creates new form InicioUI
     */
    public UIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quizButton = new javax.swing.JButton();
        rankingButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();
        rankTitle = new javax.swing.JLabel();
        pointsTitle = new javax.swing.JLabel();
        averageTitle = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        rankingTitle = new javax.swing.JLabel();
        rankInfo = new javax.swing.JLabel();
        pointsInfo = new javax.swing.JLabel();
        averageInfo = new javax.swing.JLabel();
        rankingInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        inicioLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        inicioLabel.setText("ÍNICIO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Informações:");

        quizButton.setBackground(new java.awt.Color(51, 153, 255));
        quizButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quizButton.setText("Iniciar QUIZ!");

        rankingButton.setBackground(new java.awt.Color(51, 153, 255));
        rankingButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rankingButton.setText("Ranking");
        rankingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingButtonActionPerformed(evt);
            }
        });

        disconnectButton.setBackground(new java.awt.Color(255, 0, 51));
        disconnectButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        disconnectButton.setText("Desconectar");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        rankTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rankTitle.setText("Rank:");

        pointsTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pointsTitle.setText("Pontuação:");

        averageTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        averageTitle.setText("Porcentagem de acertos:");

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piproject/api/fundo_login.png"))); // NOI18N
        fundo.setText("jLabel2");

        rankingTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rankingTitle.setText("Classificação:");

        rankInfo.setText("Falha no carregamento...");

        pointsInfo.setText("Falha no carregamento...");

        averageInfo.setText("Falha no carregamento...");

        rankingInfo.setText("Falha no carregamento...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(quizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(rankingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(averageTitle)
                            .addComponent(rankTitle)
                            .addComponent(pointsTitle)
                            .addComponent(rankingTitle)
                            .addComponent(rankInfo)
                            .addComponent(pointsInfo)
                            .addComponent(averageInfo)
                            .addComponent(rankingInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(inicioLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(disconnectButton)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(360, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(126, 126, 126)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(inicioLabel)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rankTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rankInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pointsTitle)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pointsInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(averageTitle))
                    .addComponent(rankingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(averageInfo)
                .addGap(27, 27, 27)
                .addComponent(rankingTitle)
                .addGap(18, 18, 18)
                .addComponent(rankingInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(disconnectButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel2)
                    .addContainerGap(390, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rankingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingButtonActionPerformed
        // TODO add your handling code here:
        UIRanking frame = new UIRanking();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rankingButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        inicioLabel.setText("INICIO - " + nome);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        // TODO add your handling code here:
        try (Connection con = MySQL.getConnection();){
            String updateStatus = "UPDATE `piproject`.`user_informations` set `userStatus` = 'false' where `userName`= '" + nome + "'";
            PreparedStatement pstmt = con.prepareStatement(updateStatus);
            UILogin frame = new UILogin();
            pstmt.executeUpdate();
            frame.setVisible(true);
            this.setVisible(false);
            pstmt.close();
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_disconnectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIInicio().setVisible(true);
            }
        });
    }

    private String nome = UILogin.userTextField.getText();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageInfo;
    private javax.swing.JLabel averageTitle;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JLabel fundo;
    public javax.swing.JLabel inicioLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pointsInfo;
    private javax.swing.JLabel pointsTitle;
    private javax.swing.JButton quizButton;
    private javax.swing.JLabel rankInfo;
    private javax.swing.JLabel rankTitle;
    private javax.swing.JButton rankingButton;
    private javax.swing.JLabel rankingInfo;
    private javax.swing.JLabel rankingTitle;
    // End of variables declaration//GEN-END:variables
}
