/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piproject.ui;

import piproject.mysql.MySQL;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * @author rafae
 */
public class UILogin extends javax.swing.JFrame {

    /**
     * Creates new form UILogin
     */
    public UILogin() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        userTextField = new javax.swing.JTextField();
        userPasswordField = new javax.swing.JPasswordField();
        startButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTextField.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        userTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite seu usuário:"));
        userTextField.setPreferredSize(new java.awt.Dimension(440, 65));
        getContentPane().add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 440, 65));

        userPasswordField.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        userPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite sua senha:"));
        userPasswordField.setPreferredSize(new java.awt.Dimension(440, 65));
        getContentPane().add(userPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 621, 440, -1));

        startButton.setBackground(new java.awt.Color(51, 153, 255));
        startButton.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        startButton.setText("Conectar");
        startButton.setAlignmentY(0.0F);
        startButton.setPreferredSize(new java.awt.Dimension(248, 62));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 762, 248, -1));

        registerButton.setBackground(new java.awt.Color(51, 153, 255));
        registerButton.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        registerButton.setText("Registre-se");
        registerButton.setPreferredSize(new java.awt.Dimension(142, 48));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 861, -1, -1));

        title.setFont(new java.awt.Font("Impact", 3, 96)); // NOI18N
        title.setText("          print('Quiz!')");
        title.setAlignmentX(462.0F);
        title.setAlignmentY(69.0F);
        title.setPreferredSize(new java.awt.Dimension(990, 101));
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 997, 101));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piproject/api/back.jpg"))); // NOI18N
        fundo.setText("jLabel2");
        fundo.setAlignmentY(0.0F);
        fundo.setAutoscrolls(true);
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        if (userTextField.getText().length() >= 3 && userTextField.getText().length() <= 21) {
            if (userPasswordField.getText().length() >= 3 && userPasswordField.getText().length() <= 21) {
                try (Connection con = MySQL.getConnection();) {
                    Statement stmt = con.createStatement();

                    String SQLUser = "SELECT * FROM `piproject`.`user_informations` WHERE userName='" + userTextField.getText() + "'";
                    ResultSet rs = stmt.executeQuery(SQLUser);

                    if (rs.next()) {
                        if (rs.getNString("userPassword") == null ? userPasswordField.getText() == null : rs.getNString("userPassword").equals(userPasswordField.getText())) {
                                String updateStatus = "UPDATE `piproject`.`user_informations` set `userStatus` = 'true' where `userName`= '" + userTextField.getText() + "'";
                                if (rs.getNString("userPermission").equals("user")) {
                                    JOptionPane.showMessageDialog(null, "Conectando!!!");
                                    UIInicio frame = new UIInicio();
                                    frame.setVisible(true);
                                    this.setVisible(false);
                                    PreparedStatement pstmt = con.prepareStatement(updateStatus);
                                    pstmt.executeUpdate();

                                    con.close();
                                    stmt.close();
                                    rs.close();
                                    pstmt.close();
                                } else if (rs.getNString("userPermission").equals("admin")) {
                                    JOptionPane.showMessageDialog(null, "Conectando!!!");
                                    UIInicioADM frame = new UIInicioADM();
                                    frame.setVisible(true);
                                    this.setVisible(false);
                                    PreparedStatement pstmt = con.prepareStatement(updateStatus);
                                    pstmt.executeUpdate();

                                    con.close();
                                    stmt.close();
                                    rs.close();
                                    pstmt.close();
                                } else {
                                    JOptionPane.showMessageDialog(null, "Impossível verificar sua permissão! Contatar um administrador!");
                                }
                        } else {
                            JOptionPane.showMessageDialog(null, "A senha informada está incorreta!");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Usuário inexistente!");
                    }
                } catch (Exception e) {
                    System.err.println(e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Sua senha deve conter entre 3 até 21 caracteres");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seu usuário deve conter entre 3 até 21 caracteres");
        }

    }//GEN-LAST:event_startButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        UIRegister frame = new UIRegister();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UILogin().setVisible(true);
            }
        });
    }

    public static boolean connected;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton registerButton;
    public static javax.swing.JButton startButton;
    private javax.swing.JLabel title;
    public javax.swing.JPasswordField userPasswordField;
    public static javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
