/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piproject.ui;

import piproject.mysql.MySQL;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 * @author Bidetti
 */
public class UIQuiz extends javax.swing.JFrame {


    int corretas = 0;
    int erradas = 0;
    int pergunta = 1;
    String resposta;
    public List<Integer> listID = new ArrayList<>();

    

    /**
     * Creates new form UIQuiz
     */
    public UIQuiz() {
        initComponents();
        listID.addAll(Arrays.asList(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionTitle = new javax.swing.JLabel();
        progressQuiz = new javax.swing.JProgressBar();
        progressTitle = new javax.swing.JLabel();
        questionText = new javax.swing.JLabel();
        answer3 = new javax.swing.JRadioButton();
        answer1 = new javax.swing.JRadioButton();
        answer2 = new javax.swing.JRadioButton();
        answer4 = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionTitle.setFont(new java.awt.Font("Segoe UI", 3, 96)); // NOI18N
        questionTitle.setForeground(new java.awt.Color(255, 255, 255));
        questionTitle.setText("Pergunta #1");
        questionTitle.setAlignmentY(0.0F);
        questionTitle.setAutoscrolls(true);
        questionTitle.setPreferredSize(new java.awt.Dimension(934, 186));
        getContentPane().add(questionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 934, 186));

        progressQuiz.setForeground(new java.awt.Color(102, 255, 51));
        progressQuiz.setMaximum(15);
        progressQuiz.setValue(1);
        progressQuiz.setAlignmentX(0.0F);
        progressQuiz.setAlignmentY(0.0F);
        progressQuiz.setPreferredSize(new java.awt.Dimension(200, 4));
        getContentPane().add(progressQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 240, 340, 35));

        progressTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        progressTitle.setText("Progresso: 1/15");
        getContentPane().add(progressTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 200, -1, -1));

        questionText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        questionText.setForeground(new java.awt.Color(255, 255, 255));
        questionText.setText("Erro ao carregar pergunta...");
        questionText.setToolTipText("");
        questionText.setAlignmentY(0.0F);
        questionText.setPreferredSize(new java.awt.Dimension(1444, 118));
        getContentPane().add(questionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1444, 118));

        answer3.setText("Erro ao carregar a resposta");
        answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3ActionPerformed(evt);
            }
        });
        getContentPane().add(answer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, 600, 80));

        answer1.setText("Erro ao carregar a resposta");
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });
        getContentPane().add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 600, 80));

        answer2.setText("Erro ao carregar a resposta");
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });
        getContentPane().add(answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 600, 80));

        answer4.setText("Erro ao carregar a resposta");
        answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4ActionPerformed(evt);
            }
        });
        getContentPane().add(answer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 670, 600, 80));

        nextButton.setBackground(new java.awt.Color(51, 153, 255));
        nextButton.setFont(new java.awt.Font("Impact", 1, 40)); // NOI18N
        nextButton.setText("Próximo");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 920, 317, 74));

        cancelButton1.setBackground(new java.awt.Color(51, 153, 255));
        cancelButton1.setFont(new java.awt.Font("Impact", 1, 40)); // NOI18N
        cancelButton1.setText("Cancelar");
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 920, 317, 74));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piproject/api/back.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if (pergunta < 15) {
            pergunta = pergunta + 1;
            progressQuiz.setValue(pergunta);
            progressTitle.setText(String.format("Progresso: %d/15", pergunta));
            questionTitle.setText(String.format("Pergunta #%d", pergunta));
            String SQLQuestions = "SELECT * FROM `piproject`.`questions` WHERE questionID=?";
            Random random = new Random();
            int elementId = random.nextInt(listID.size());
            int elementIndex = listID.get(elementId);
            Integer elementRemoved = listID.remove(elementId);
            System.err.println(elementRemoved + " removed!");
            System.out.println(listID);
        } else {
                        JOptionPane.showMessageDialog(null, "QUIZ finalizado! Voltando a tela inicial");
                        UIInicio frameuser = new UIInicio();
                        frameuser.setVisible(true);
                        this.setVisible(false);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        // TODO add your handling code here:
        try (Connection con = MySQL.getConnection();) {
            String updateStatus = "UPDATE `piproject`.`user_informations` set `userStatus` = 'false' where `userName`= '" + nome + "'";
            PreparedStatement pstmt = con.prepareStatement(updateStatus);
            JOptionPane.showMessageDialog(null, "QUIZ cancelado, sistema finalizando...");
            pstmt.executeUpdate();
            pstmt.close();
            con.close();
            this.dispose();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
        resposta = "A";
    }//GEN-LAST:event_answer1ActionPerformed

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
        // TODO add your handling code here:
        resposta = "B";
    }//GEN-LAST:event_answer2ActionPerformed

    private void answer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4ActionPerformed
        // TODO add your handling code here:
        resposta = "C";
    }//GEN-LAST:event_answer4ActionPerformed

    private void answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3ActionPerformed
        // TODO add your handling code here:
        resposta = "D";
    }//GEN-LAST:event_answer3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIQuiz().setVisible(true);
                
            }
        });
    }

    private String nome = UILogin.userTextField.getText();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answer1;
    private javax.swing.JRadioButton answer2;
    private javax.swing.JRadioButton answer3;
    private javax.swing.JRadioButton answer4;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton nextButton;
    public javax.swing.JProgressBar progressQuiz;
    private javax.swing.JLabel progressTitle;
    private javax.swing.JLabel questionText;
    private javax.swing.JLabel questionTitle;
    // End of variables declaration//GEN-END:variables
}
