/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piproject.ui;

import piproject.mysql.MySQL;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 * @author Bidetti
 */
public class UIQuiz extends javax.swing.JFrame {


    int pontos;
    int pergunta = 1;
    String resposta;
    public List<Integer> listID = new ArrayList<>();
    Random random = new Random();
    int antigoIndex;


    /**
     * Creates new form UIQuiz
     */
    public UIQuiz() {
        initComponents();
        this.setLocationRelativeTo(null);
        listID.addAll(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15));
        try (Connection con = MySQL.getConnection();) {
            Statement stmt = con.createStatement();
            int elementId = random.nextInt(listID.size());
            int elementIndex = listID.get(elementId);
            antigoIndex = elementIndex;
            String SQLQuestions = "SELECT * FROM `piproject`.`questions` WHERE questionID=" + elementIndex;
            listID.remove(elementId);
            ResultSet rsQr = stmt.executeQuery(SQLQuestions);
            if (rsQr.next()) {
                questionText.setText("<html><p style=\"width:1400px\">" + rsQr.getNString("question") + "</html>");
                answer1.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerA") + "</html>");
                answer2.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerB") + "</html>");
                answer3.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerC") + "</html>");
                answer4.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerD") + "</html>");
            }
            stmt.close();
            rsQr.close();
        } catch (Exception e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionTitle = new javax.swing.JLabel();
        progressQuiz = new javax.swing.JProgressBar();
        progressTitle = new javax.swing.JLabel();
        questionText = new javax.swing.JLabel();
        answer3 = new javax.swing.JRadioButton();
        answer1 = new javax.swing.JRadioButton();
        answer2 = new javax.swing.JRadioButton();
        answer4 = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionTitle.setFont(new java.awt.Font("Segoe UI", 3, 96)); // NOI18N
        questionTitle.setForeground(new java.awt.Color(255, 255, 255));
        questionTitle.setText("Pergunta #1");
        questionTitle.setAlignmentY(0.0F);
        questionTitle.setAutoscrolls(true);
        questionTitle.setPreferredSize(new java.awt.Dimension(934, 186));
        getContentPane().add(questionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -40, 934, 186));

        progressQuiz.setForeground(new java.awt.Color(102, 255, 51));
        progressQuiz.setMaximum(15);
        progressQuiz.setValue(1);
        progressQuiz.setAlignmentX(0.0F);
        progressQuiz.setAlignmentY(0.0F);
        progressQuiz.setPreferredSize(new java.awt.Dimension(200, 4));
        getContentPane().add(progressQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 240, 340, 35));

        progressTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        progressTitle.setText("Progresso: 1/15");
        getContentPane().add(progressTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 200, -1, -1));

        questionText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        questionText.setForeground(new java.awt.Color(255, 255, 255));
        questionText.setText("Erro ao carregar pergunta...");
        questionText.setToolTipText("");
        questionText.setAlignmentY(0.0F);
        questionText.setPreferredSize(new java.awt.Dimension(1444, 118));
        getContentPane().add(questionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 1444, 230));

        answer3.setText("Erro ao carregar a resposta");
        answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3ActionPerformed(evt);
            }
        });
        getContentPane().add(answer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 400, 750, 225));

        answer1.setText("Erro ao carregar a resposta");
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });
        getContentPane().add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 750, 225));

        answer2.setText("Erro ao carregar a resposta");
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });
        getContentPane().add(answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 750, 225));

        answer4.setText("Erro ao carregar a resposta");
        answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4ActionPerformed(evt);
            }
        });
        getContentPane().add(answer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 650, 750, 225));

        nextButton.setBackground(new java.awt.Color(51, 153, 255));
        nextButton.setFont(new java.awt.Font("Impact", 1, 40)); // NOI18N
        nextButton.setText("Próximo");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 920, 317, 74));

        cancelButton1.setBackground(new java.awt.Color(51, 153, 255));
        cancelButton1.setFont(new java.awt.Font("Impact", 1, 40)); // NOI18N
        cancelButton1.setText("Cancelar");
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 920, 317, 74));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piproject/api/back.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        answer1.setSelected(false);
        answer2.setSelected(false);
        answer3.setSelected(false);
        answer4.setSelected(false);
        if (pergunta < 15) {
            try (Connection con = MySQL.getConnection();) {
                Statement stmt = con.createStatement();
                String SQLAnswer = "SELECT `isCorrect` FROM `piproject`.`questions` WHERE questionID=" + antigoIndex;
                ResultSet rsAnswer = stmt.executeQuery(SQLAnswer);
                if (rsAnswer.next()) {
                    if (resposta.equals(rsAnswer.getNString("isCorrect"))) {
                        pontos = pontos + 10;
                    }
                }
                int elementId = random.nextInt(listID.size());
                int elementIndex = listID.get(elementId);
                antigoIndex = elementIndex;
                pergunta = pergunta + 1;
                progressQuiz.setValue(pergunta);
                progressTitle.setText(String.format("Progresso: %d/15", pergunta));
                questionTitle.setText(String.format("Pergunta #%d", pergunta));
                String SQLQuestions = "SELECT * FROM `piproject`.`questions` WHERE questionID=" + elementIndex;
                listID.remove(elementId);
                ResultSet rsQr = stmt.executeQuery(SQLQuestions);
                if (rsQr.next()) {
                    questionText.setText("<html><p style=\"width:1400px\">" + rsQr.getNString("question") + "</html>");
                    answer1.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerA") + "</html>");
                    answer2.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerB") + "</html>");
                    answer3.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerC") + "</html>");
                    answer4.setText("<html><p style=\"width:700px\">" + rsQr.getNString("answerD") + "</html>");
                }
                stmt.close();
                rsAnswer.close();
                rsQr.close();
            } catch (Exception e) {
                System.err.println(e);
            }
        } else {
            String rank = "ferro";
            if (pontos <= 49) {
                rank = "Ferro";
            } else if (pontos >= 50 && pontos <= 99) {
                rank = "Ouro";
            } else if (pontos >= 100 && pontos <= 150) {
                rank = "Diamante";
            }
            String updatePoints = "UPDATE `piproject`.`user_informations` SET userPoints = "+pontos+", userRank = \""+rank+"\" where `userName` =\""+ nome +"\"";
            try (Connection con = MySQL.getConnection();) {
                PreparedStatement pstmt = con.prepareStatement(updatePoints);
                pstmt.executeUpdate();
                String SQLFinal = "SELECT * FROM `piproject`.`user_informations` where `userName` = '"+nome+"'";
                Statement stmt = con.createStatement();
                ResultSet rsFinal = stmt.executeQuery(SQLFinal);
                if (rsFinal.next()) {
                    int userID = rsFinal.getInt("userID");
                    String userRank = rsFinal.getNString("userRank");
                    int userPoints = rsFinal.getInt("userPoints");
                    JOptionPane.showMessageDialog(null, String.format("Parabéns, %s! Você finalizou o QUIZ.\n \nInformações:\n  ID: %d\n    Rank: %s\n  Pontuação: %d", nome,userID, userRank, userPoints));
                }
                stmt.close();
                rsFinal.close();
                pstmt.close();
                con.close();
            } catch (Exception e) {
                System.out.println(e);
            }
            
            UIInicio frameuser = new UIInicio();
            this.setVisible(false);
            frameuser.setVisible(true);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        // TODO add your handling code here:
        try (Connection con = MySQL.getConnection();) {
            String updateStatus = "UPDATE `piproject`.`user_informations` set `userStatus` = 'false' where `userName`= '" + nome + "'";
            PreparedStatement pstmt = con.prepareStatement(updateStatus);
            JOptionPane.showMessageDialog(null, "QUIZ cancelado, sistema finalizando...");
            pstmt.executeUpdate();
            pstmt.close();
            con.close();
            this.dispose();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
        resposta = "A";
    }//GEN-LAST:event_answer1ActionPerformed

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
        // TODO add your handling code here:
        resposta = "B";
    }//GEN-LAST:event_answer2ActionPerformed

    private void answer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4ActionPerformed
        // TODO add your handling code here:
        resposta = "D";
    }//GEN-LAST:event_answer4ActionPerformed

    private void answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3ActionPerformed
        // TODO add your handling code here:
        resposta = "C";
    }//GEN-LAST:event_answer3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIQuiz().setVisible(true);
            }
        });
    }

    private String nome = UILogin.userTextField.getText();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answer1;
    private javax.swing.JRadioButton answer2;
    private javax.swing.JRadioButton answer3;
    private javax.swing.JRadioButton answer4;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton nextButton;
    public javax.swing.JProgressBar progressQuiz;
    private javax.swing.JLabel progressTitle;
    private javax.swing.JLabel questionText;
    private javax.swing.JLabel questionTitle;
    // End of variables declaration//GEN-END:variables
}
