/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piproject.ui;

import piproject.mysql.MySQL;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * @author rafae
 */
public class UIRegister extends javax.swing.JFrame {

    /**
     * Creates new form UILogin
     */
    public UIRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        userTextField = new javax.swing.JTextField();
        userPasswordField = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Crie seu usuário:"));
        getContentPane().add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 463, 440, 69));

        userPasswordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Crie sua senha:"));
        getContentPane().add(userPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 621, 440, 69));

        createButton.setBackground(new java.awt.Color(51, 153, 255));
        createButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        createButton.setText("Criar");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 796, 174, 54));

        voltarButton.setBackground(new java.awt.Color(51, 153, 255));
        voltarButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 796, 174, 54));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Impact", 3, 96)); // NOI18N
        title.setText("print('Quiz!')");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 69, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piproject/api/back.jpg"))); // NOI18N
        fundo.setText("jLabel2");
        fundo.setAlignmentY(0.0F);
        fundo.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed

        if (userTextField.getText().length() >= 3 && userTextField.getText().length() <= 21) {
            if (userPasswordField.getText().length() >= 3 && userPasswordField.getText().length() <= 21) {
                try (Connection con = MySQL.getConnection();) {
                    Statement stmt = con.createStatement();

                    String SQLUser = "SELECT * FROM `piproject`.`user_informations` WHERE userName='" + userTextField.getText() + "'";
                    ResultSet rs = stmt.executeQuery(SQLUser);

                    if (rs.next() == false) {
                        PreparedStatement insertUser = con.prepareStatement("INSERT INTO `piproject`.`user_informations` (`userName`, `userPassword`) VALUES ('" + userTextField.getText() + "', '" + userPasswordField.getText() + "');");
                        insertUser.execute();
                        JOptionPane.showMessageDialog(null, "Usuário criado com sucesso. Conecte-se!");

                        UILogin frame = new UILogin();
                        frame.setVisible(true);
                        this.setVisible(false);

                        stmt.close();
                        rs.close();
                        insertUser.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuário já existente!");
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Sua senha deve conter entre 3 até 21 caracteres");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seu usuário deve conter entre 3 até 21 caracteres");
        }

    }//GEN-LAST:event_createButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        UILogin frame = new UILogin();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createButton;
    private javax.swing.JLabel fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel title;
    public javax.swing.JPasswordField userPasswordField;
    public javax.swing.JTextField userTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
